---
name: Checks

# Trigger below i.e. on push do this
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    # executes command by
    runs-on: ubuntu-20.04
    steps:
      # logs into dockerhub
      - name: Login to Docker Hub
      # use another premade action provided in github actions
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # premade to check our code inside the job running
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
